/* eslint-disable */
/**
 * Generated by convex - placeholder for TypeScript.
 * The real file is generated when you run `npx convex dev`.
 * 
 * This placeholder provides type stubs so the app compiles.
 */
import type { FunctionReference } from "convex/server";

// Placeholder API object - will be replaced by real generated code
export const api: any = {
  rescuers: { list: "rescuers:list" },
  vehicles: { list: "vehicles:list" },
  incidents: { list: "incidents:list", assignRescuers: "incidents:assignRescuers" },
  zones: { list: "zones:list" },
  scheduleEntries: { list: "scheduleEntries:list" },
  seed: { seed: "seed:seed" },
};

export const internal: any = {};
